# Study-level Evaluator
- **df_metadata** (real-world DICOM metadata)
    - `study_id`: Study identifier
    - `file_id`: DICOM file identifier
    - `IOD`: DICOM Information Object Definition (IOD)
    - `Tag`: DICOM Tag
    - `Value`: Tag value
- **df_standard** (DICOM standard definition)
    - `IOD`: DICOM IOD
    - `Tag`: DICOM Tag
    - `Attribute Name`: DICOM Tag's Attribute Name

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
import sys
dir_function = '../DicomStandardEvaluator/Evaluator'
sys.path.append(dir_function)

In [3]:
data_dir = '/nfs/project/WellcomeHDN/kch-mr/metadata/dicom_heterogeneity'
output_dir = '/nfs/project/WellcomeHDN/kch-mr/metadata/dicom_heterogeneity'

## Data Set (DICOM Metadata)
**Columns**:
- **IOD**: IOD Specification according to `(0008,0016) SOP Class UID` ([Table B.5-1.Standard SOP Classes](https://dicom.nema.org/medical/Dicom/2025c/output/chtml/part04/sect_B.5.html))
- **study_id**: unique id per dicom studies 
- **series_id**: unique id per dicom series
- **file_id**: unique id per dicom instances
- **Manufacturer (optional)**: `(0008,0070) Manufacturer` - e.g., 'Siemens Healthineers', 'GE Healthcare',
       'Canon Medical Systems Corporation', 'Philips Healthcare',
       'Hitachi Healthcare Corporation', 'Shimadzu Corporation',
       'AI Lab Co., Ltd.', 'Scimedix Corporation', 'Agfa HealthCare N.V.',
       'Carestream Health, Inc.',
       'Konica Minolta Healthcare Americas, Inc.', None, 'Hologic, Inc.',
       'MEDI-FUTURE, Inc.', 'IMS Giotto S.p.A.', 'FUJIFILM Corporation',
       'GENORAY Co., Ltd.', 'DRTech Corporation'
- **ScannerModel (optional)**: - `(0008,1090) Manufacturer's Model Name` e.g., 'SOMATOM Definition AS', 'LightSpeed16', 'Asteion', 'HiSpeed',
       'SOMATOM Spirit', 'SOMATOM Perspective', 'CT/e', 'LightSpeed',
       'BrightSpeed', 'Brilliance 6', 'Pronto', 'LightSpeed VCT',
       'SOMATOM Definition Flash', 'SOMATOM Definition AS+', 'Aquilion',
       'Brilliance 16', 'SOMATOM Emotion Duo', 'SOMATOM Emotion 6',
       'Optima CT660', 'SOMATOM Emotion 16', 'Alexion', 'Biograph20',
       None, 'Mx8000', 'SOMATOM Volume Zoom', 'Supria',
       'Brilliance iCT 256', 'ProSpeed FII', 'Sytec SRi', 'Brilliance 64',
       'SCT-4800TC', 'AIRIS Vento', 'MAGNETOM Essenza', 'MAGNETOM Avanto',
       'Signa Excite 1.5T', 'Achieva', 'GoldSeal Signa HDxt', 'Ingenia',
       'Intera', 'Genesis Signa', 'AIRIS II', 'MAGNETOM Espree',
       'MagFinder II', 'MAGNETOM Trio', 'Discovery MR750w',
       'Signa profile excite', 'Optima MR430s 1.5T', 'SM160',
       'MAGNETOM Skyra', 'ADC', 'CLASSIC CR', '0862', 'Senographe DS',
       'KODAK DirectView CR 975', 'Lorad Selenia', 'CR 85-X', 'BRESTIGE',
       'CR 75', 'GIOTTO IMAGE MD', 'MAMMOMAT Inspiration',
       'Senographe 2000D', 'KODAK DirectView CR 850',
       'Selenia Dimensions', 'FCR 5000 CR', 'DMX-600', 'RSM 1824C'
- **Tag**
- **AttributeName**
- **Value**

In [4]:
df_dataset= pd.read_csv(os.path.join(data_dir, 'df_metadata_kch-mr.csv'), dtype=str)

In [5]:
df_dataset.head()

,IOD,study_id,series_id,file_id,Manufacturer,ScannerModel,Tag,AttributeName,Value
0,MR Image IOD,1.3.46.670589.11.0.0.11.4.2.0.17178.5.4512.200...,1.3.46.670589.11.0.0.11.4.2.0.17178.5.4196.200...,/nfs/project/WellcomeHDN/kch/sourcedata/dicom/...,Philips Medical Systems,Achieva,"(0008,0008)",ImageType,['ORIGINAL' 'PRIMARY' 'M_FFE' 'M' 'FFE']
1,MR Image IOD,1.3.46.670589.11.0.0.11.4.2.0.17178.5.4512.200...,1.3.46.670589.11.0.0.11.4.2.0.17178.5.4196.200...,/nfs/project/WellcomeHDN/kch/sourcedata/dicom/...,Philips Medical Systems,Achieva,"(0008,0008)",ImageType,['ORIGINAL' 'PRIMARY' 'M_FFE' 'M' 'FFE']
2,MR Image IOD,1.3.46.670589.11.0.0.11.4.2.0.17178.5.4512.200...,1.3.46.670589.11.0.0.11.4.2.0.17178.5.3652.200...,/nfs/project/WellcomeHDN/kch/sourcedata/dicom/...,Philips Medical Systems,Achieva,"(0008,0008)",ImageType,['ORIGINAL' 'PRIMARY' 'M_FFE' 'M' 'FFE']
3,MR Image IOD,1.3.46.670589.11.0.0.11.4.2.0.17178.5.4512.200...,1.3.46.670589.11.0.0.11.4.2.0.17178.5.3652.200...,/nfs/project/WellcomeHDN/kch/sourcedata/dicom/...,Philips Medical Systems,Achieva,"(0008,0008)",ImageType,['ORIGINAL' 'PRIMARY' 'MPR' 'M' 'FFE']
4,MR Image IOD,1.3.46.670589.11.0.0.11.4.2.0.17178.5.4512.200...,1.3.46.670589.11.0.0.11.4.2.0.17178.5.3652.200...,/nfs/project/WellcomeHDN/kch/sourcedata/dicom/...,Philips Medical Systems,Achieva,"(0008,0008)",ImageType,['ORIGINAL' 'PRIMARY' 'M_FFE' 'M' 'FFE']

In [7]:
def table_1(df):
    summary = pd.DataFrame({
        'n_manufacturer': df.groupby('IOD', dropna=False)['Manufacturer'].nunique(),
        'n_scannermodel': df.groupby('IOD', dropna=False)['ScannerModel'].nunique(),
        'n_study_global': df.groupby('IOD', dropna=False)['study_id'].nunique(),
        'n_series_global': df.groupby('IOD', dropna=False)['series_id'].nunique(),
        'n_file_global': df.groupby('IOD', dropna=False)['file_id'].nunique(),
        'n_tag': df.groupby('IOD', dropna=False)['Tag'].size(),
        'n_tag/n_file': df.groupby('IOD', dropna=False)['Tag'].size()/df.groupby('IOD', dropna=False)['file_id'].nunique()
    })
    return summary

summary = table_1(df_dataset)
summary.to_csv(os.path.join(output_dir, 'summary_counts.csv'))
summary

,n_manufacturer,n_scannermodel,n_study_global,n_series_global,n_file_global,n_tag,n_tag/n_file
IOD,,,,,,,
MR Image IOD,12,32,83219,789581,790580,23550783,29.789247

## Reference Set (DICOM Standard 2025c)
- Mandatory Modality-specific Modules

In [8]:
# 2025c standard
df_standard = pd.read_excel("../files/DicomStandardReference_2025c/C2025MandatoryModalityspecificModules_ReferenceSet.xlsx")
print(f"2025c standard: {len(df_standard)} rows with {df_standard['Tag'].nunique()} unique tags")

2025c standard: 216 rows with 164 unique tags

In [9]:
display(df_standard.groupby('IOD')['Tag'].nunique())
display(df_standard.head(1))

IOD
CT Image IOD                           57
Computed Radiography Image IOD         31
Digital Mammography X-Ray Image IOD    72
MR Image IOD                           56
Name: Tag, dtype: int64

,IOD,IE,Module,Tag,Attribute Name,Keyword,Type,VR,VM,Attribute Description,Source,Standard Terms,Type_Group
0,Computed Radiography Image IOD,Image,CR_Image,"(0028,0004)",Photometric Interpretation,Photometric​Interpretation,1,CS,1,Specifies the intended interpretation of the p...,Table C.8-2. CR Image Module Attributes,"{'Enumerated Values': ['MONOCHROME1', 'MONOCHR...",Required

## Evaluation

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ast
import tabulate
import sys

sys.path.append('Evaluator')
from DicomCodeStandardEvaluator import DicomCodeStandardEvaluator

In [11]:
#df_standard = df_standard.copy()
#df_dataset = df_dataset.copy() 

print(f'Standard: {df_standard.shape[0]} rows with {df_standard['Tag'].nunique()} unique tags')
print(f'Dataset: {df_dataset.shape[0]} rows with {df_dataset['Tag'].nunique()} unique tags')

Standard: 216 rows with 164 unique tags
Dataset: 23550783 rows with 48 unique tags

### Completeness (Study-level)

In [12]:
from DicomCodeStandardEvaluator_withoutVR import DicomCodeStandardEvaluator_withoutVR # Completeness Only (No need for 'VR')
evaluator_2025c = DicomCodeStandardEvaluator_withoutVR(df_dataset, df_standard)

In [ ]:
study_rates_2025c, study_stats_2025c = evaluator_2025c.analyze_rates_with_stats(group_cols=['IOD', 'study_id', 'Manufacturer', 'ScannerModel'])

#### study_rates_2025c

In [157]:
# Information Completeness Index (ICI) = tag existence x value existence
study_rates_2025c['ICI'] = study_rates_2025c['tag_existence_rate'] * study_rates_2025c['value_existence_rate']

# Manufacturer, ScannerModel
iod_study_rates_2025c = pd.merge(study_rates_2025c, df_dataset[['IOD', 'study_id', 'Manufacturer', 'ScannerModel']].drop_duplicates(keep='first'), on = ['IOD', 'study_id'], how='left')
iod_study_rates_2025c.head()

,Tag,Attribute Name,total_files,files_with_tag,files_with_value,tag_existence_rate,value_existence_rate,IOD,study_id,Manufacturer_x,ScannerModel_x,ICI,Manufacturer_y,ScannerModel_y
0,"(0008,0008)",Image Type,14,14,14,1.0,1.0,MR Image IOD,1.2.124.113532.10.136.102.24.20101206.112337.5...,GE MEDICAL SYSTEMS,Signa HDxt,1.0,GE MEDICAL SYSTEMS,Signa HDxt
1,"(0028,0002)",Samples per Pixel,14,14,14,1.0,1.0,MR Image IOD,1.2.124.113532.10.136.102.24.20101206.112337.5...,GE MEDICAL SYSTEMS,Signa HDxt,1.0,GE MEDICAL SYSTEMS,Signa HDxt
2,"(0028,0004)",Photometric Interpretation,14,14,14,1.0,1.0,MR Image IOD,1.2.124.113532.10.136.102.24.20101206.112337.5...,GE MEDICAL SYSTEMS,Signa HDxt,1.0,GE MEDICAL SYSTEMS,Signa HDxt
3,"(0028,0100)",Bits Allocated,14,14,14,1.0,1.0,MR Image IOD,1.2.124.113532.10.136.102.24.20101206.112337.5...,GE MEDICAL SYSTEMS,Signa HDxt,1.0,GE MEDICAL SYSTEMS,Signa HDxt
4,"(0028,0101)",Bits Stored,14,14,14,1.0,1.0,MR Image IOD,1.2.124.113532.10.136.102.24.20101206.112337.5...,GE MEDICAL SYSTEMS,Signa HDxt,1.0,GE MEDICAL SYSTEMS,Signa HDxt

In [158]:
# SAVE
study_rates_2025c.to_excel(os.path.join(output_dir, 'study_rates_2025c.xlsx'), index=False) 
iod_study_rates_2025c.to_excel(os.path.join(output_dir, 'iod_study_rates_2025c.xlsx'), index=False)

ValueError: This sheet is too large! Your sheet size is: 1234016, 12 Max sheet size is: 1048576, 16384

In [159]:
# Try summarising by Manufacturer and ScannerModel
# Count
manufacturer_n = study_rates_2025c.drop_duplicates(subset='study_id').groupby(['IOD', 'Manufacturer', 'ScannerModel']).agg({
    'study_id': ['count'],
}).reset_index()
manufacturer_n.columns = ['IOD', 'Manufacturer', 'ScannerModel', 'n_studies']
manufacturer_n.head()

            IOD        Manufacturer      ScannerModel  n_studies
0  MR Image IOD  GE MEDICAL SYSTEMS   DISCOVERY MR450       3172
1  MR Image IOD  GE MEDICAL SYSTEMS   DISCOVERY MR750       1414
2  MR Image IOD  GE MEDICAL SYSTEMS  DISCOVERY MR750w         36
3  MR Image IOD  GE MEDICAL SYSTEMS     GENESIS_SIGNA        153
4  MR Image IOD  GE MEDICAL SYSTEMS     Optima MR450w        313

In [160]:
# Only use tag existence rate, because in this dataset all tags that exist have values (value existence is only 0 or 1)
study_rates_2025c['Make Model'] = study_rates_2025c['Manufacturer'] + ' ' + study_rates_2025c['ScannerModel']
manufacturer_exist = study_rates_2025c.groupby(['IOD', 'Tag', 'Attribute Name', 'Make Model']).agg({
    'tag_existence_rate': ['mean', 'std'],
}).reset_index()
manufacturer_exist.fillna(0, inplace=True)  # Set SD for groups with only one study to 0 instead of NaN to avoid it mucking up aggregation later
manufacturer_exist.head()

            IOD          Tag Attribute Name  \

0  MR Image IOD  (0008,0008)     Image Type
1  MR Image IOD  (0008,0008)     Image Type
2  MR Image IOD  (0008,0008)     Image Type
3  MR Image IOD  (0008,0008)     Image Type
4  MR Image IOD  (0008,0008)     Image Type

                            Make Model tag_existence_rate
                                                     mean  std
0   GE MEDICAL SYSTEMS DISCOVERY MR450                1.0  0.0
1   GE MEDICAL SYSTEMS DISCOVERY MR750                1.0  0.0
2  GE MEDICAL SYSTEMS DISCOVERY MR750w                1.0  0.0
3     GE MEDICAL SYSTEMS GENESIS_SIGNA                1.0  0.0
4     GE MEDICAL SYSTEMS Optima MR450w                1.0  0.0

In [161]:
# Pivot
manufacturer_exist.columns = ['IOD', 'Tag', 'Attribute Name', 'Make Model', 'mean', 'std']
manufacturer_exist_mean = manufacturer_exist.pivot_table(index=['IOD', 'Tag', 'Attribute Name'], columns=['Make Model'], values=['mean'], aggfunc='sum').reset_index()
manufacturer_exist_std = manufacturer_exist.pivot_table(index=['IOD', 'Tag', 'Attribute Name'], columns=['Make Model'], values=['std'], aggfunc='sum').reset_index()
manufacturer_exist_mean.columns = [' '.join(col).strip().replace('mean ', '') for col in manufacturer_exist_mean.columns]
manufacturer_exist_std.columns = [' '.join(col).strip().replace('std ', '') for col in manufacturer_exist_std.columns]
manufacturer_exist_mean.head()

,IOD,Tag,Attribute Name,GE MEDICAL SYSTEMS DISCOVERY MR450,GE MEDICAL SYSTEMS DISCOVERY MR750,GE MEDICAL SYSTEMS DISCOVERY MR750w,GE MEDICAL SYSTEMS GENESIS_SIGNA,GE MEDICAL SYSTEMS Optima MR450w,GE MEDICAL SYSTEMS SIGNA Artist,GE MEDICAL SYSTEMS SIGNA EXCITE,...,SIEMENS Avanto,SIEMENS Espree,SIEMENS Skyra,SIEMENS Sonata,SIEMENS Symphony,SIEMENS SymphonyTim,SIEMENS TrioTim,Siemens Healthineers MAGNETOM Vida,TOSHIBA Titan,TOSHIBA_MEC MRT200PP3
0,MR Image IOD,"(0008,0008)",Image Type,1.000000,1.000000,1.00000,1.000000,1.000000,1.0,1.000000,...,1.000000,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.0,1.0
1,MR Image IOD,"(0008,2218)",Anatomic Region Sequence,0.104867,0.067185,0.00000,0.000000,0.196843,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
2,MR Image IOD,"(0008,2228)",Primary Anatomic Structure Sequence,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,MR Image IOD,"(0018,0020)",Scanning Sequence,0.901542,0.996269,0.95845,0.823165,0.845362,1.0,0.995439,...,0.999325,1.0,1.0,1.0,1.0,1.0,0.925926,1.0,1.0,1.0
4,MR Image IOD,"(0018,0021)",Sequence Variant,0.901542,0.996269,0.95845,0.823165,0.845362,1.0,0.995439,...,0.999325,1.0,1.0,1.0,1.0,1.0,0.925926,1.0,1.0,1.0

In [162]:
# Save
with pd.ExcelWriter(os.path.join(output_dir, 'manufacturer_stats_2025c_200-400k.xlsx')) as xl:
    manufacturer_n.to_excel(xl, sheet_name='N', index=False)
    manufacturer_exist_mean.to_excel(xl, sheet_name='tag_existence_mean', index=False)
    manufacturer_exist_std.to_excel(xl, sheet_name='tag_existence_std', index=False)

#### study_stats_2025c

In [163]:
print(study_stats_2025c.shape)
study_stats_2025c.head()

(112, 11)

,IOD,Tag,Attribute Name,Metric,Mean,Std,CV(%),Min,Max,Range,n_groups
0,MR Image IOD,"(0008,0008)",Image Type,tag_existence_rate,0.999967,0.003710,0.370975,0.5,1.0,0.5,22036
1,MR Image IOD,"(0008,0008)",Image Type,value_existence_rate,1.000000,0.000000,0.000000,1.0,1.0,0.0,22036
2,MR Image IOD,"(0008,2218)",Anatomic Region Sequence,tag_existence_rate,0.023836,0.142564,598.101599,0.0,1.0,1.0,22036
3,MR Image IOD,"(0008,2218)",Anatomic Region Sequence,value_existence_rate,0.027637,0.163933,593.173708,0.0,1.0,1.0,22036
4,MR Image IOD,"(0008,2228)",Primary Anatomic Structure Sequence,tag_existence_rate,0.000000,0.000000,NaN,0.0,0.0,0.0,22036

In [164]:
# 1. Convert to pivot table (create wide-format columns for each metric and statistic)
study_stats_2025c_wide = study_stats_2025c.pivot_table(
    index=['IOD', 'Tag', 'n_groups'],
    columns='Metric',
    values=['Mean', 'Std']
).reset_index()

# 2. Clean up column names (MultiIndex → single column)
study_stats_2025c_wide.columns = ['_'.join(col).strip('_') for col in study_stats_2025c_wide.columns.values]

# 3. Reorder columns
cols = ['IOD', 'Tag'] + \
       [col for col in study_stats_2025c_wide.columns if 'tag_existence_rate' in col] + \
       [col for col in study_stats_2025c_wide.columns if 'value_existence_rate' in col] + \
       [col for col in study_stats_2025c_wide.columns if 'value_standardization_rate' in col] + \
       [col for col in study_stats_2025c_wide.columns if 'value_diversity' in col] + \
       ['n_groups']
study_stats_2025c_wide = study_stats_2025c_wide[cols]
study_stats_2025c_wide.head(2)

,IOD,Tag,Mean_tag_existence_rate,Std_tag_existence_rate,Mean_value_existence_rate,Std_value_existence_rate,n_groups
0,MR Image IOD,"(0008,0008)",0.999967,0.003710,1.000000,0.000000,22036
1,MR Image IOD,"(0008,2218)",0.023836,0.142564,0.027637,0.163933,22036

In [165]:
# Merge with df_standard
iod_study_stats_2025c = pd.merge(study_stats_2025c_wide, df_standard, on=['IOD', 'Tag'], how='left')
iod_study_stats_2025c = iod_study_stats_2025c[['IOD', 'Tag', 'Attribute Name', 'Type', 'Type_Group', 
       'Attribute Description', 'Source', 'n_groups', 
       'Mean_tag_existence_rate', 'Std_tag_existence_rate',
       'Mean_value_existence_rate', 'Std_value_existence_rate'
       ]]
iod_study_stats_2025c.head()

,IOD,Tag,Attribute Name,Type,Type_Group,Attribute Description,Source,n_groups,Mean_tag_existence_rate,Std_tag_existence_rate,Mean_value_existence_rate,Std_value_existence_rate
0,MR Image IOD,"(0008,0008)",Image Type,1,Required,Image identification characteristics. See Sect...,Table C.8-4. MR Image Module Attributes,22036,0.999967,0.003710,1.000000,0.000000
1,MR Image IOD,"(0008,2218)",Anatomic Region Sequence,3,Optional,Sequence that identifies the anatomic region o...,Table 10-7. General Anatomy Optional Macro Att...,22036,0.023836,0.142564,0.027637,0.163933
2,MR Image IOD,"(0008,2228)",Primary Anatomic Structure Sequence,3,Optional,Sequence of Items that identifies the primary ...,Table 10-8. Primary Anatomic Structure Macro A...,22036,0.000000,0.000000,0.000000,0.000000
3,MR Image IOD,"(0018,0020)",Scanning Sequence,1,Required,Description of the type of data taken.,Table C.8-4. MR Image Module Attributes,22036,0.968707,0.122865,0.988428,0.106951
4,MR Image IOD,"(0018,0021)",Sequence Variant,1,Required,Variant of the Scanning Sequence.,Table C.8-4. MR Image Module Attributes,22036,0.968707,0.122865,0.988428,0.106951

In [166]:
# SAVE
study_stats_2025c.to_excel(os.path.join(output_dir, 'study_stats_2025c_MR_200-400k.xlsx'), index=False)
iod_study_stats_2025c.to_excel(os.path.join(output_dir, 'iod_study_stats_2025c_MR_200-400k.xlsx'), index=False)